<?php

namespace AppBundle\Repository;

/**
 * MailerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailerRepository extends \Doctrine\ORM\EntityRepository
{
}
